// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrgJimnOac6kVGENATe6jGrIbOcDQvPhk',
    appId: '1:921368661200:web:0572c15f21634af53e62d5',
    messagingSenderId: '921368661200',
    projectId: 'swirl-1856f',
    authDomain: 'swirl-1856f.firebaseapp.com',
    databaseURL: 'https://swirl-1856f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'swirl-1856f.firebasestorage.app',
    measurementId: 'G-CCXQJB0T7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzShbcwRNQzzUPiWHVlDd12DIJsd6x_FE',
    appId: '1:921368661200:android:e6834cf49e9b9a803e62d5',
    messagingSenderId: '921368661200',
    projectId: 'swirl-1856f',
    databaseURL: 'https://swirl-1856f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'swirl-1856f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNqzrQqYNZI8ZFtKmlqtQweDKrILh6lB0',
    appId: '1:921368661200:ios:d311433b82f308473e62d5',
    messagingSenderId: '921368661200',
    projectId: 'swirl-1856f',
    databaseURL: 'https://swirl-1856f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'swirl-1856f.firebasestorage.app',
    androidClientId: '921368661200-1uh6qg8v5057qh2p6g0h11co00o68gbt.apps.googleusercontent.com',
    iosClientId: '921368661200-kcokd792sl0usmlpnc5qtcepojb0cr0h.apps.googleusercontent.com',
    iosBundleId: 'com.swirl',
  );
}
